# Generated by Django 6.0 on 2026-01-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_Metadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, help_text='Versión actual del dataset', verbose_name='Versión')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('hash', models.CharField(blank=True, help_text='Hash MD5/SHA256 del dataset para verificación', max_length=64, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'Cache de Metadatos',
                'verbose_name_plural': 'Cache de Metadatos',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto de la recomendación extraído del post', verbose_name='Texto')),
                ('sentimiento', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutral', 'Neutral')], default='neutral', help_text='Análisis de sentimiento (positivo/negativo/neutral)', max_length=50, verbose_name='Sentimiento')),
                ('confianza', models.FloatField(default=0.0, help_text='Nivel de confianza del análisis NLP (0-1)', verbose_name='Confianza')),
                ('votos_utilidad', models.IntegerField(default=0, help_text='Cantidad de votos positivos de la comunidad', verbose_name='Votos de Utilidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='academic.catedra', verbose_name='Cátedra')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
