# Generated by Django 6.0 on 2026-01-07 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='contribuidor',
            field=models.ForeignKey(blank=True, help_text='Usuario que contribuyó esta recomendación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuciones', to=settings.AUTH_USER_MODEL, verbose_name='Contribuidor'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='post_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='scraping.post_scrapeado', verbose_name='Post Origen'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='sesion_scraping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='scraping.sesion_scraping', verbose_name='Sesión de Scraping'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['catedra', '-fecha_creacion'], name='recommendat_catedra_2611e0_idx'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['sentimiento'], name='recommendat_sentimi_391c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['-votos_utilidad'], name='recommendat_votos_u_406b0f_idx'),
        ),
    ]
