# Generated by Django 6.0 on 2026-01-07 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_comision_docente_and_more'),
        ('recommendations', '0002_initial'),
        ('scraping', '0004_tarea_scrapeo_activa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recomendacion',
            name='recommendat_catedra_2611e0_idx',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistencia Obligatoria'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='comision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='academic.comision', verbose_name='Comisión'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='docent_perf',
            field=models.JSONField(blank=True, default=dict, help_text='Atributos extraídos del docente', verbose_name='Perfil Docente'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='parciales_tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Parciales'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='prob_aprobar',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('desconocido', 'Desconocido')], default='desconocido', max_length=50, verbose_name='Probabilidad de Aprobar'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='toma_tp',
            field=models.BooleanField(default=False, verbose_name='Toma TP'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['comision', '-fecha_creacion'], name='recommendat_comisio_edae43_idx'),
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='catedra',
        ),
    ]
