# Generated by Django 6.0 on 2026-01-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('url', models.URLField(help_text='URL del grupo de Facebook', unique=True, verbose_name='URL')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('prioridad', models.IntegerField(default=0, help_text='Mayor prioridad = se scrapea más frecuentemente', verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sesion_Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('error', 'Error')], default='iniciado', max_length=50, verbose_name='Estado')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('keywords_procesadas', models.JSONField(default=list, help_text='Lista de keywords que se procesaron en esta sesión', verbose_name='Keywords Procesadas')),
                ('posts_encontrados', models.IntegerField(default=0, verbose_name='Posts Encontrados')),
                ('recomendaciones_nuevas', models.IntegerField(default=0, verbose_name='Recomendaciones Nuevas')),
            ],
            options={
                'verbose_name': 'Sesión de Scraping',
                'verbose_name_plural': 'Sesiones de Scraping',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarea_Scrapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(help_text='Lista de keywords para buscar en el grupo', verbose_name='Palabras Clave')),
                ('busquedas_pendientes', models.JSONField(help_text='Keywords que aún no han sido procesados', verbose_name='Búsquedas Pendientes')),
                ('frecuencia', models.CharField(default='semanal', help_text='Qué tan seguido actualizar (diaria, semanal, mensual)', max_length=50, verbose_name='Frecuencia')),
                ('posts_encontrados', models.IntegerField(default=0, verbose_name='Posts Encontrados')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tarea de Scraping',
                'verbose_name_plural': 'Tareas de Scraping',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Post_Scrapeado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='Identificador único del post en Facebook', max_length=200, unique=True, verbose_name='ID del Post')),
                ('texto', models.TextField(verbose_name='Texto del Post')),
                ('autor', models.CharField(blank=True, help_text='Nombre del autor (anonimizado si es necesario)', max_length=200, verbose_name='Autor')),
                ('procesado', models.BooleanField(default=False, help_text='Si ya se procesó con NLP para extraer recomendaciones', verbose_name='Procesado')),
                ('fecha_post', models.DateTimeField(blank=True, help_text='Fecha original del post en Facebook', null=True, verbose_name='Fecha del Post')),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Scraping')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scraping.grupos', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Post Scrapeado',
                'verbose_name_plural': 'Posts Scrapeados',
                'ordering': ['-fecha_scraping'],
            },
        ),
    ]
