# Generated by Django 6.0 on 2026-01-07 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion_scraping',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_scraping', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='post_scrapeado',
            name='sesion_scraping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='scraping.sesion_scraping', verbose_name='Sesión de Scraping'),
        ),
        migrations.AddField(
            model_name='tarea_scrapeo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='scraping.grupos', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='sesion_scraping',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='scraping.tarea_scrapeo', verbose_name='Tarea'),
        ),
        migrations.AddIndex(
            model_name='post_scrapeado',
            index=models.Index(fields=['post_id'], name='scraping_po_post_id_b1aa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='post_scrapeado',
            index=models.Index(fields=['procesado'], name='scraping_po_procesa_848ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='post_scrapeado',
            index=models.Index(fields=['grupo', '-fecha_scraping'], name='scraping_po_grupo_i_9635fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea_scrapeo',
            index=models.Index(fields=['grupo', '-fecha_creacion'], name='scraping_ta_grupo_i_5679aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion_scraping',
            index=models.Index(fields=['usuario', '-inicio'], name='scraping_se_usuario_6827d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion_scraping',
            index=models.Index(fields=['estado'], name='scraping_se_estado_c24a5d_idx'),
        ),
    ]
