# Generated by Django 6.0 on 2026-01-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_scrapeado',
            name='fecha_post',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Post'),
        ),
    ]
