# Generated by Django 6.0 on 2026-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_post_scrapeado_fecha_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_scrapeo',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si la tarea está habilitada para ejecutarse', verbose_name='Activa'),
        ),
    ]
