# Generated by Django 6.0 on 2026-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribuciones_aprobadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='puede_scrapear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('colaborador', 'Colaborador Scraping'), ('moderador', 'Moderador'), ('admin', 'Administrador')], default='estudiante', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='sesiones_scraping_activas',
            field=models.IntegerField(default=0),
        ),
    ]
