# Generated by Django 6.0 on 2026-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cátedra', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('titular', models.CharField(max_length=200, verbose_name='Profesor Titular')),
                ('mencion_fb', models.IntegerField(default=0, help_text='Cantidad de veces mencionada en posts', verbose_name='Menciones en Facebook')),
                ('ano', models.IntegerField(blank=True, help_text='Año de la carrera (1, 2, 3, etc.)', null=True, verbose_name='Año')),
                ('ultima_actualizacion_scraping', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activa', models.BooleanField(default=True, help_text='Si la cátedra está activa actualmente', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cátedra',
                'verbose_name_plural': 'Cátedras',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='academic_ca_codigo_08ff8a_idx'), models.Index(fields=['titular'], name='academic_ca_titular_308acf_idx'), models.Index(fields=['activa'], name='academic_ca_activa_7ca03f_idx')],
            },
        ),
    ]
