# Generated by Django 6.0 on 2026-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único de la comisión', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('numero_catedra', models.IntegerField(blank=True, null=True, verbose_name='Número Cátedra')),
                ('horario', models.TextField(blank=True, null=True, verbose_name='Horario')),
                ('cuatrimestre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuatrimestre')),
                ('mencion_fb', models.IntegerField(default=0, help_text='Cantidad de veces mencionada en posts', verbose_name='Menciones en Facebook')),
                ('ano', models.IntegerField(blank=True, help_text='Año de la carrera (1, 2, 3, etc.)', null=True, verbose_name='Año')),
                ('ultima_actualizacion_scraping', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activa', models.BooleanField(default=True, help_text='Si la cátedra está activa actualmente', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, verbose_name='Nombre Completo')),
                ('alias_search', models.TextField(blank=True, help_text='Para búsquedas', verbose_name='Alias Search')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.RemoveIndex(
            model_name='catedra',
            name='academic_ca_codigo_08ff8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='catedra',
            name='academic_ca_titular_308acf_idx',
        ),
        migrations.RemoveIndex(
            model_name='catedra',
            name='academic_ca_activa_7ca03f_idx',
        ),
    ]
