# Generated by Django 6.0 on 2026-01-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_comision_docente_and_more'),
        ('recommendations', '0003_remove_recomendacion_recommendat_catedra_2611e0_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catedra',
        ),
        migrations.AddField(
            model_name='comision',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='academic.docente', verbose_name='Docente'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['codigo'], name='academic_co_codigo_175601_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['activa'], name='academic_co_activa_75aa1a_idx'),
        ),
    ]
