# Generated by Django 6.0 on 2026-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_delete_catedra_comision_docente_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comision',
            name='academic_co_codigo_175601_idx',
        ),
        migrations.AddField(
            model_name='comision',
            name='codigo_actividad',
            field=models.CharField(blank=True, default='', help_text='Código de la materia (ej: 205, 2X8, 73U, 85S)', max_length=50, verbose_name='Código de Actividad'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='codigo',
            field=models.CharField(help_text='Código único de la comisión en el sistema de la facultad', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('codigo', 'docente', 'horario', 'cuatrimestre')},
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['codigo', 'cuatrimestre'], name='academic_co_codigo_171368_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['docente', 'cuatrimestre'], name='academic_co_docente_0eb1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['codigo_actividad'], name='academic_co_codigo__e7c6b0_idx'),
        ),
    ]
