# Generated by Django 6.0 on 2026-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_comision_academic_co_codigo_175601_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='bibliografia_info',
            field=models.TextField(blank=True, help_text='Detalles sobre el material de estudio', null=True, verbose_name='Información de Bibliografía'),
        ),
        migrations.AddField(
            model_name='comision',
            name='llegada_docente',
            field=models.CharField(blank=True, choices=[('buena', 'Buena llegada a los estudiantes'), ('mala', 'Mala llegada a los estudiantes'), ('regular', 'Llegada regular')], help_text='Cómo es la relación docente-estudiante', max_length=20, null=True, verbose_name='Llegada del Docente'),
        ),
        migrations.AddField(
            model_name='comision',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Remota', 'Remota'), ('Híbrida', 'Híbrida')], help_text='Modalidad de dictado de la comisión', max_length=50, null=True, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='comision',
            name='nivel_aprobados',
            field=models.CharField(blank=True, choices=[('alto', 'Alta tasa de aprobados'), ('medio', 'Tasa media de aprobados'), ('bajo', 'Baja tasa de aprobados')], help_text='Nivel de aprobación de estudiantes', max_length=20, null=True, verbose_name='Nivel de Aprobados'),
        ),
        migrations.AddField(
            model_name='comision',
            name='recomendacion_procesada',
            field=models.BooleanField(default=False, help_text='Indica si el scraper ya procesó la recomendación', verbose_name='Recomendación Procesada'),
        ),
        migrations.AddField(
            model_name='comision',
            name='recomendacion_raw',
            field=models.TextField(blank=True, help_text='Texto original de la recomendación sin procesar', null=True, verbose_name='Recomendación (texto original)'),
        ),
        migrations.AddField(
            model_name='comision',
            name='tipo_catedra',
            field=models.CharField(blank=True, choices=[('recomendable', 'Cátedra Recomendable'), ('no_recomendable', 'Cátedra NO Recomendable'), ('exigente', 'Cátedra Exigente'), ('para_aprender', 'Cátedra para Aprender'), ('accesible', 'Cátedra Accesible')], help_text='Clasificación según probabilidad de aprobar', max_length=20, null=True, verbose_name='Tipo de Cátedra'),
        ),
        migrations.AddField(
            model_name='comision',
            name='tipo_parciales',
            field=models.CharField(blank=True, help_text='Descripción de los parciales (escrito, oral, MC, etc.)', max_length=100, null=True, verbose_name='Tipo de Parciales'),
        ),
        migrations.AddField(
            model_name='comision',
            name='toma_asistencia',
            field=models.BooleanField(blank=True, help_text='Si la cátedra toma asistencia o no', null=True, verbose_name='Toma Asistencia'),
        ),
        migrations.AddField(
            model_name='comision',
            name='toma_trabajos_practicos',
            field=models.BooleanField(blank=True, help_text='Si la cátedra da trabajos prácticos', null=True, verbose_name='Toma Trabajos Prácticos'),
        ),
    ]
