# Generated by Django 6.0 on 2026-01-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_comision_sede_es_centro_externo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comision',
            new_name='academic_co_sede_9f5ed2_idx',
            old_name='academic_co_sede_12ab86_idx',
        ),
        migrations.RenameIndex(
            model_name='comision',
            new_name='academic_co_es_cent_0a99c0_idx',
            old_name='academic_co_es_cent_7f2f53_idx',
        ),
    ]
